table base_fake_dados
	lineageTag: 6981729c-bc4d-42f6-9520-71d970de036b

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 566c1523-08a9-4464-a090-90688d8b8362
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Nome
		dataType: string
		lineageTag: 9e4afe84-6180-4431-a4c1-27bf18cc8aef
		summarizeBy: none
		sourceColumn: Nome

		annotation SummarizationSetBy = Automatic

	column 'Data de Nascimento'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4b745915-a710-436f-81dd-085e2a876b44
		summarizeBy: none
		sourceColumn: Data de Nascimento

		variation Variation
			isDefault
			relationship: a9cb8fa9-3f9e-4cea-8559-4d8dc39d3bdc
			defaultHierarchy: LocalDateTable_1c2c75d7-f94f-470f-aa69-cd9b168ef3c0.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Cargo
		dataType: string
		lineageTag: c04d9902-eec7-4661-b4c9-f4e59f7476a3
		summarizeBy: none
		sourceColumn: Cargo

		annotation SummarizationSetBy = Automatic

	column Salário
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: b07e3644-19b9-47fa-8432-c55cdcb8abf3
		summarizeBy: sum
		sourceColumn: Salário

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column Sexo
		dataType: string
		lineageTag: b5aaded3-0d5e-4271-ad68-9060b8b703db
		summarizeBy: none
		sourceColumn: Sexo

		annotation SummarizationSetBy = Automatic

	column 'Setor de Atuação'
		dataType: string
		lineageTag: 2deea544-fd67-46d2-bc10-f0b280502036
		summarizeBy: none
		sourceColumn: Setor de Atuação

		annotation SummarizationSetBy = Automatic

	column Idade
		dataType: int64
		formatString: 0
		lineageTag: f37bd59b-6595-4905-acfe-fe3930c96844
		summarizeBy: sum
		sourceColumn: Idade

		annotation SummarizationSetBy = Automatic

	partition base_fake_dados = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\user\Desktop\GitLeo\DashboardRh-Correto\RH\arquivos_csv\base_fake_dados.csv"),[Delimiter=";", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Valor Substituído" = Table.ReplaceValue(#"Cabeçalhos Promovidos",".",",",Replacer.ReplaceText,{"Salário"}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Valor Substituído",{{"ID", Int64.Type}, {"Nome", type text}, {"Data de Nascimento", type date}, {"Cargo", type text}, {"Salário", Currency.Type}, {"Sexo", type text}, {"Setor de Atuação", type text}}),
				    #"Idade Inserida" = Table.AddColumn(#"Tipo Alterado", "Idade", each (Date.From(DateTime.LocalNow()) - [Data de Nascimento])/365, type duration),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Idade Inserida",{{"Idade", Int64.Type}})
				in
				    #"Tipo Alterado1"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

