table Medidas
	lineageTag: 1dfd2418-9705-4b31-b6ac-327ba9e0fb84

	measure Qtd_funcionarios =
			
			COUNTROWS(base_fake_dados)
		formatString: 0
		lineageTag: d9ed6ed6-f17c-4ad0-a1c3-19c12fa05948

	measure funcionarios_M = ```
			
			CALCULATE(
			    [Qtd_funcionarios], 
			    FILTER(base_fake_dados,base_fake_dados[Sexo] = "Masculino")
			)
			```
		formatString: 0
		lineageTag: 2cc4c6e8-d3e2-40c1-bc86-beac05a50946

	measure funcionarios_F = ```
			
			CALCULATE(
			    [Qtd_funcionarios], 
			    FILTER(base_fake_dados,base_fake_dados[Sexo] = "Feminino")
			)
			```
		formatString: 0
		lineageTag: 361b2be0-de68-462c-948f-a69047e2e534

	measure salario_medio =
			
			AVERAGE(base_fake_dados[Salário])
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: c444754b-4a68-40e5-b470-9775d13fd3a0

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure idade_media = AVERAGE(base_fake_dados[Idade])
		formatString: 0
		lineageTag: f009bc72-4a61-4f19-a904-93e1fb3f44b4

		annotation PBI_FormatHint = {"isDecimal":true}

	partition Medidas = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Coluna 1", type text}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"Coluna 1"})
				in
				    #"Colunas Removidas"

	annotation PBI_ResultType = Table

