table Medidas
	lineageTag: 1dfd2418-9705-4b31-b6ac-327ba9e0fb84

	measure Qtd_funcionarios =
			
			COUNTROWS(base_fake_dados)
		formatString: #,0
		displayFolder: 😊Colaboradores
		lineageTag: d9ed6ed6-f17c-4ad0-a1c3-19c12fa05948

	measure funcionarios_M = ```
			
			CALCULATE(
			    [Qtd_funcionarios], 
			    FILTER(base_fake_dados,base_fake_dados[Sexo] = "Masculino")
			)
			```
		formatString: 0
		displayFolder: 😊Colaboradores
		lineageTag: 2cc4c6e8-d3e2-40c1-bc86-beac05a50946

	measure funcionarios_F = ```
			
			CALCULATE(
			    [Qtd_funcionarios], 
			    FILTER(base_fake_dados,base_fake_dados[Sexo] = "Feminino")
			)
			```
		formatString: 0
		displayFolder: 😊Colaboradores
		lineageTag: 361b2be0-de68-462c-948f-a69047e2e534

	measure salario_medio =
			
			CALCULATE(
			    AVERAGE(base_fake_dados[Salário]),
			    FILTER(base_fake_dados , base_fake_dados[Vigente] = "Ativo")
			)
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: 🎲Calculos
		lineageTag: c444754b-4a68-40e5-b470-9775d13fd3a0

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure idade_media = AVERAGE(base_fake_dados[Idade])
		formatString: 0
		displayFolder: 😊Colaboradores
		lineageTag: f009bc72-4a61-4f19-a904-93e1fb3f44b4

		annotation PBI_FormatHint = {"isDecimal":true}

	measure TempoDeCasa = AVERAGE(base_fake_dados[Tempo_de_casa])
		formatString: 0
		displayFolder: 😊Colaboradores
		lineageTag: a884f082-6286-4a29-b154-4ebe59367f4f

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Qtd_funcionarios_admitidos MoM%' =
			
			IF(
				ISFILTERED('base_fake_dados'[Data_admissao]),
				ERROR("Medidas rápidas de inteligência de tempo somente podem ser agrupadas ou filtradas pela hierarquia de data fornecida pelo Power BI ou pela coluna de data primária."),
				VAR __PREV_MONTH =
					CALCULATE(
						[Qtd_funcionarios],
						DATEADD('base_fake_dados'[Data_admissao].[Date], -1, MONTH)
					)
				RETURN
					DIVIDE([Qtd_funcionarios] - __PREV_MONTH, __PREV_MONTH)
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 🎲Calculos
		lineageTag: 3f19b10e-2e27-45d8-9034-86d9d20ae70a

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MonthOverMonth"
				}

		changedProperty = FormatString

	measure 'Qtd_funcionarios_desligados MoM%' =
			
			IF(
				ISFILTERED('base_fake_dados'[Data_admissao]),
				ERROR("Medidas rápidas de inteligência de tempo somente podem ser agrupadas ou filtradas pela hierarquia de data fornecida pelo Power BI ou pela coluna de data primária."),
				VAR __PREV_MONTH =
					CALCULATE(
						[Qtd_funcionarios],
						DATEADD('base_fake_dados'[data_demissão].[Date], -1, MONTH)
					)
				RETURN
					DIVIDE([Qtd_funcionarios] - __PREV_MONTH, __PREV_MONTH)
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 🎲Calculos
		lineageTag: f031cd7e-bf29-41da-abf9-4f465fe284eb

	measure Qtd_desligamentos = ```
			
			
			CALCULATE(
			    [Qtd_funcionarios], 
			    FILTER(base_fake_dados , base_fake_dados[data_demissão] <> BLANK()))
			```
		formatString: 0
		displayFolder: 😊Colaboradores
		lineageTag: 8c345f8f-568f-4f56-8657-220c5c3978bf

	measure 'salario MoM%' =
			
			IF(
				ISFILTERED('base_fake_dados'[Data_admissao]),
				ERROR("Medidas rápidas de inteligência de tempo somente podem ser agrupadas ou filtradas pela hierarquia de data fornecida pelo Power BI ou pela coluna de data primária."),
				VAR __PREV_MONTH =
					CALCULATE(
						[salario_medio],
						DATEADD('base_fake_dados'[Data_admissao].[Date], -1, MONTH)
					)
				RETURN
					DIVIDE([salario_medio] - __PREV_MONTH, __PREV_MONTH)
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 🎲Calculos
		lineageTag: 113bf8d9-77af-4cd0-a30a-460e78433fa3

	measure soma_salario =
			
			CALCULATE(
			SUM(base_fake_dados[Salário]),
			FILTER(base_fake_dados , base_fake_dados[Vigente] = "Ativo")
			)
		formatString: "R$"#,0.00;-"R$"#,0.00;"R$"#,0.00
		displayFolder: 🎲Calculos
		lineageTag: a4b67984-1e94-453c-b308-5416eb751eb6

		annotation PBI_FormatHint = {"currencyCulture":"es-BR"}

	partition Medidas = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Coluna 1", type text}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"Coluna 1"})
				in
				    #"Colunas Removidas"

	annotation PBI_ResultType = Table

